# Generated by Django 6.0.3 on 2026-03-27 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='ize',
            new_name='size',
        ),
    ]
