# Generated by Django 6.0.3 on 2026-03-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_rename_ize_tenant_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='company_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='tenant',
            name='subdomain_prefix',
            field=models.CharField(default='test', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
